### ISSUE TITLE
Meta Package Project notes

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoBase.jl#1]
This package holds the entire original register module in Yao.jl. It will include a default register implemented on CPU and definitions of abstract interfaces for registers.

**Comment by GiggleLiu** [comment]
A memo of what we should put in this repo

https://docs.google.com/presentation/d/1Uaa7yR9-Cg-Xhzpr5pcIzpPENTON5mzqj9fAg2CALvs/edit?usp=sharing

- [ ] Part of Intrinsics, general_apply!, general_mat, basis
- [x] `AbstractRegister` Interface
- [ ] Gate specific applys, redirected to general ones by default.

**Comment by GiggleLiu** [comment]
A few comments on abstract register

DEFINE `interface` of type `A`: functions define A, and do not have fall back implementations. e.g. `getindex` and `size` are interfaces of `AbstractArray`.

## Required Register Interfaces
These functions defines Register, but do not have fall back implementation (interfaces)
* [x] nactive, nqubits
* [x] cunapply! # the most general `apply!` function
* [x] measure
* [x] remove!, set!, insert_qubits!
* [x] focus!, relax!
* [x] repeat, viewbatch

Here, `addbit!` -> `insert_qubit!` (note: this interface has been realized somewhere), the latter is more general, so that the former can have a fall back implementation.
`remove!` and `reset!` are designed to provide fallback to `measure_remove!`, `measure_reset!`. Although for `DefaultRegister`, they have better implementations. `measure!` can also fall back to `measure` + `set!`.

## Optional Register Interfaces
* [x] select  # for cheating
* [x] density_matrix

## Functions with fall back implementations
* [x] (?apply!, c?apply!) for ? in [:x, :y, :z, :h, :t, :s, :sdag, :tdag]
* [x] u1apply!
* [x] measure_remove!, measure_reset!, measure!
* [x] join  # insert_qubit! + set!
* [x] zero_state, product_state, rand_state

## APIs do not need inheritance at all
* [x] `nremain(register)`, `basis`
* [x] `nbatch` and `datatype`

## The following APIs should not exist
* `state`, it is for `DefaultRegister` only.
* `BitStr` duplicate with `product_state(nbit, 0b111101)`.

**It is a heavy work with a lot of redesign. But I think it worth to make the interfaces perfect!** 💯

**Comment by Roger-luo** [comment]
A name change, what about 

`cnuapply!` -> `general_unitary_apply!` or some other longer name.

This is not a user API, so I guess a longer name is better.

**Comment by GiggleLiu** [comment]
Here, I don't think so.
The role of YaoBase is like blas/lapack, these functions are not interfaces. Developers must read documents to understand how to use these functions. The consistency of naming is much more important. like current `xapply!`, `cxapply!`, `unapply!`, `cunapply!` are consistent.

BTW: I think you mean `general_controlled_unitary_apply!`. It is tooooo long

Note: `un` mean `U(N)` matrix, which means general unitary matrix.

**Comment by GiggleLiu** [comment]
Maybe using symbols is better? like `apply!(::Val{:X}, ...)`

**Comment by Roger-luo** [comment]
yes, I would prefer symbols instead of a lot different names:

1. the meaning can be misleading, e.g `unapply!` could mean the reverse operation of `apply!`, etc.
2. they are just different implementation of the function `apply!` with different inputs, not necessary to have different names

And I don't think BLAS use different names for different types is because of the design, it is just because C/Fortran do not have generic types and function overloading, and this actually became a problem without meta-programming while trying to wrap them.

Since this part of method for `apply!` function will directly take some builtin types, and block/register/etc. will have their own type. we can just use the following syntax without worrying any conflict. This makes this part even more independent.

```julia
apply!(state::AbstractVecOrMat, U::AbstractMatrix, locs::NTuple)
apply!(state::AbstractVecOrMat, U0::AbstractMatrix, locs::NTuple{M, Int}, cbits::NTuple{C, Int}, cvals::NTuple{C, Int}) where {C, M}
```

the documentation can just be

```julia
"""
     apply!(state, U, locs[, cbits, cvals]) -> state

apply an unitary to the quantum state (a matrix (aka `AbstractMatrix`) or a vector 
(aka `AbstractVector`)) at given locations `locs`. Optional arguments are control qubits.
"""
```

Which make sense not only for the interface, but also for the implementation, since

https://github.com/QuantumBFS/Yao.jl/blob/b1b22cd846605a7d91f1c4e8b579903fbeb19771/src/Intrinsics/GeneralApply.jl#L62

```julia
unapply!(state::AbstractVecOrMat, U::AbstractMatrix, locs::NTuple) = cunapply!(state, (), (), U, locs)
```

For `u1apply`, this can actually be dispatched by

```julia
apply!(state::AbstractVecOrMat, U::AbstractMatrix, locs::Union{NTuple{1, Int}, Int})
```

which also prevent you from accidentally using **general unitary apply** for single qubit unitary.


This is even sweet for users, since if you don't like any abstraction, just directly write

```julia
state = rand(16)
U = rand_unitary(4) # NOTE: this might be a useful util we could provide
apply!(state, U, locs)
```

Regarding to specialized code, like `Pauli X`, we could just use `Symbol` as the unitary (instead of a real `Array`/`SparseMatrixCSC`)

```julia

@inline apply!(state, x::Symbol, locs) = apply!(state, Val(x), locs)

function apply!(state, ::Val{:X}, locs) # = xapply!
end

apply!(state, :X, locs)
```

In this way, all the `apply!` function will just work when you input something intuitively without reading much documentation. And I think that's why we like multiple dispatch.

**Comment by Roger-luo** [comment]
Some discussion with @GiggleLiu : we will use `instruct!` to distinguish those method with `apply!` for `register` abstraction and `block` abstraction.

Since `apply!(vec, block)` shouldn't just work for any vector. The batch and active qubit information is required.
